### ISSUE TITLE
simple.py doesn't recognise ovf file

### ISSUE THREAD

**Issue by Skyrme** [spirit-code/ovf#9]
running simple.py creates the attached testfile_py.ovf which isn't recognised as an ovf file according to its output on the console. 

[testfile_py.ovf.txt](https://github.com/spirit-code/ovf/files/2531366/testfile_py.ovf.txt)
[output.txt](https://github.com/spirit-code/ovf/files/2531381/output.txt)

**Comment by GPMueller** [comment]
Fixed with bdfa526853e9f34893c75324d34ddf6341922564 and in the release v0.4.1.
